"""first revision

迁移 ID: 9184f669f130
父迁移: 
创建时间: 2024-10-28 15:39:36.315913

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9184f669f130'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('weather',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_qqbot_next_qquuidmapping',
    sa.Column('qq_id', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('qq_id', name=op.f('pk_mc_qqbot_next_qquuidmapping')),
    sa.UniqueConstraint('uuid'),
    info={'bind_key': 'mc_qqbot_next'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mc_qqbot_next_qquuidmapping')
    # ### end Alembic commands ###
