"""add create time for message_target

迁移 ID: 91fc7bca2d32
父迁移: e9f78ad5efa2
创建时间: 2024-11-01 14:13:49.911437

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '91fc7bca2d32'
down_revision: str | Sequence[str] | None = 'e9f78ad5efa2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_target', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
