"""first revision

迁移 ID: e9f78ad5efa2
父迁移: 
创建时间: 2024-10-31 16:17:09.340103

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e9f78ad5efa2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('mc-qqbot-next',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_player_info',
    sa.Column('uuid', sa.String(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_mc_player_info')),
    info={'bind_key': 'mc_qqbot_next'}
    )
    op.create_table('message_target',
    sa.Column('message_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('target_server', sa.String(), nullable=True),
    sa.Column('target_player', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_message_target')),
    info={'bind_key': 'mc_qqbot_next'}
    )
    op.create_table('qq_uuid_mapping',
    sa.Column('qq_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['mc_player_info.uuid'], name=op.f('fk_qq_uuid_mapping_uuid_mc_player_info')),
    sa.PrimaryKeyConstraint('qq_id', name=op.f('pk_qq_uuid_mapping')),
    sa.UniqueConstraint('uuid'),
    info={'bind_key': 'mc_qqbot_next'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qq_uuid_mapping')
    op.drop_table('message_target')
    op.drop_table('mc_player_info')
    # ### end Alembic commands ###
